In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing/reading data
from matplotlib import pyplot as plt 

In [2]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [3]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255
_,m_train = X_train.shape

In [4]:
Y_train

array([7, 7, 1, ..., 9, 5, 4])

In [5]:
def init_params(): 
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z)/sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1 # Z1 = W1*A1 + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def deriv_ReLU(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [6]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1,b1, W2, b2

In [7]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[1 0 7 ... 1 2 1] [7 7 1 ... 9 5 4]
0.051829268292682924
Iteration:  10
[7 0 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.10948780487804878
Iteration:  20
[7 0 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.15934146341463415
Iteration:  30
[7 7 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.20670731707317072
Iteration:  40
[7 7 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.2455609756097561
Iteration:  50
[7 7 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.280609756097561
Iteration:  60
[7 7 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.31117073170731707
Iteration:  70
[7 7 0 ... 4 0 1] [7 7 1 ... 9 5 4]
0.33963414634146344
Iteration:  80
[7 7 1 ... 4 0 1] [7 7 1 ... 9 5 4]
0.37885365853658537
Iteration:  90
[7 7 1 ... 4 5 2] [7 7 1 ... 9 5 4]
0.43370731707317073
Iteration:  100
[7 7 1 ... 4 5 6] [7 7 1 ... 9 5 4]
0.47504878048780486
Iteration:  110
[9 7 1 ... 9 5 6] [7 7 1 ... 9 5 4]
0.5115365853658537
Iteration:  120
[9 7 1 ... 9 5 6] [7 7 1 ... 9 5 4]
0.545829268292683
Iteration:  130
[9 7 1 ... 9 5 6] [7 7 1 ... 9 5 4]
0.5768780487804878
Iteration